emojis = [
    { unicode = "ğŸ˜³", path = "flosh.png" },
    { unicode = "ğŸ˜", path = "trol.png" },
    { unicode = "ğŸ¸", path = "monkaStare.png" },
    { unicode = "ğŸ™‚", path = "pauseChamp.png" },
    { unicode = "ğŸ˜", path = "weirdChamp.png" },
    { unicode = "ğŸ˜„", path = "peepoHappy.png" },

    # Example definitions:
    #{ unicode = "[wideChamp]", path = "weirdChamp.png" },
    #{ unicode = "[widePeepo]", path = "peepoHappy.png" },
    #{ unicode = "ğŸ˜„", path = "peepoHappy.png", width = 8, height = 4 },
]
