emojis = [
    { unicode = "ğŸ˜³", path = "flosh.png" },
    { unicode = "ğŸ˜", path = "trol.png" },
    { unicode = "ğŸ¸", path = "monkaStare.png" },
    { unicode = "ğŸ™‚", path = "pauseChamp.png" },
    { unicode = "ğŸ˜", path = "weirdChamp.png" },
]
