emojis = [
    { unicode = "\u1F633", path = "flosh.png" }, # ğŸ˜³
    { unicode = "\u1F601", path = "trol.png" }, # ğŸ˜
    { unicode = "\u1F438", path = "monkaStare.png" }, # ğŸ¸
    { unicode = "\u1F642", path = "pauseChamp.png" }, # ğŸ™‚
    { unicode = "\u1F610", path = "weirdChamp.png" }, # ğŸ˜
    { unicode = "\u1F604", path = "peepoHappy.png" }, # ğŸ˜„
    { unicode = "\u1F99D", path = "they is stuck.jpg", width = 24, height = 8 }, # ğŸ¦

    # Example definitions:
    #{ unicode = "[wideChamp]", path = "weirdChamp.png" },
    #{ unicode = "[widePeepo]", path = "peepoHappy.png" },
    #{ unicode = "ğŸ˜„", path = "peepoHappy.png", width = 8, height = 4 },
]
